In [1]:
import numpy as np

# Slicing:

In [2]:
arr1=np.arange(1,13).reshape(3,4)

In [3]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr1[0,0]

1

In [7]:
arr1[0,0].ndim #0 that means it is scalar

0

In [9]:
arr1[0]

array([1, 2, 3, 4])

In [11]:
arr1[:,0]        #creates 1-D array of first element in all row 

array([1, 5, 9])

In [13]:
arr1[:,0:1] #2-d array of all the first elements in each row

array([[1],
       [5],
       [9]])

In [14]:
arr1[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [15]:
arr1[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr1[::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr1[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr1.itemsize

4

In [19]:
arr1.dtype

dtype('int32')

In [ ]:
32/8