# Concatenation and split

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,21).reshape(4,5)

In [3]:
arr2=np.arange(21,41).reshape(4,5)

In [4]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [6]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [9]:
np.concatenate((arr1,arr2),axis=0) #adding data column wise 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [10]:
np.concatenate((arr1,arr2),axis=1)#adding data row wise ---> like this

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35],
       [16, 17, 18, 19, 20, 36, 37, 38, 39, 40]])

In [11]:
#concatenate without using axis
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35],
       [16, 17, 18, 19, 20, 36, 37, 38, 39, 40]])

In [12]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

# Split:

In [15]:
np.split(arr1,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
arr2=np.array([1,2,3,4])
arr3=arr2.reshape(4,1)
arr2=np.hstack((arr1,arr3))

In [25]:
arr2

array([[ 1,  2,  3,  4,  5,  1],
       [ 6,  7,  8,  9, 10,  2],
       [11, 12, 13, 14, 15,  3],
       [16, 17, 18, 19, 20,  4]])

In [28]:
list1=np.split(arr2,2)

In [29]:
type(list1)

list

In [30]:
np.split(arr2,2,axis=1)

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18]]),
 array([[ 4,  5,  1],
        [ 9, 10,  2],
        [14, 15,  3],
        [19, 20,  4]])]

In [31]:
list1

[array([[ 1,  2,  3,  4,  5,  1],
        [ 6,  7,  8,  9, 10,  2]]),
 array([[11, 12, 13, 14, 15,  3],
        [16, 17, 18, 19, 20,  4]])]