In [1]:
import numpy as np


# Mathemetical Operations using Numpy

In [18]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)

In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
arr1+arr2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [23]:
arr1-arr2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [24]:
np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [25]:
arr1*arr2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [26]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [27]:
arr1 @ arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [28]:
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [29]:
arr1.max

<function ndarray.max>

In [30]:
arr1.max()

9

In [32]:
arr1.argmax() #to give index of maximum element in array

8

In [34]:
arr1.max(axis=0)#0-for column 1-for row

array([7, 8, 9])

In [35]:
arr1.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [36]:
arr1.min()

1

In [37]:
arr1.argmin()

0

In [38]:
arr1.min(axis=1)

array([1, 4, 7])

In [40]:
arr1.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [51]:
np.sum(arr1)

45

In [52]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [53]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [54]:
np.std(arr1)

2.581988897471611

In [48]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [56]:
np.mean(arr1)

5.0

In [57]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [58]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])