In [1]:
import numpy as np

In [2]:
arr1=[[1,1,1],[1,1,1],[1,1,1]]

In [4]:
print(arr1)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


In [9]:
arr1=np.ones(3)

In [10]:
print(arr1)

[1. 1. 1.]


In [11]:
arr2=np.ones((3,3))

In [12]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr2.dtype

dtype('float64')

In [14]:
arr2=np.ones((3,3),dtype=int)

In [15]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
arr3=np.zeros((3,3))

In [17]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr4=np.zeros((3,3),dtype=bool)

In [19]:
arr4

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
arr5=np.zeros((3,3),dtype=str)

In [21]:
arr5

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [26]:
arr5=np.empty((2,2))

In [27]:
print(arr5)

[[0. 0.]
 [0. 0.]]
